export default [
  {
    title: "GILDA DE ANCHOA",
    englishTitle: "GILDA DE ANCHOA",
    description: "Olivas, anchoas de cantábrico y piparra.",
    englishDescription: "Olive, Cantabrian anchovies, and piparra pepper.",
    price: 3,
    unit: true,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "PAN ARTESANAL",
    englishTitle: "HANDMADE BREAD",
    description:
      "Mogaza de masa madre, acompañado de nuestro allioli, tomate valenciano rallado y nuestra salsa del dia",
    englishDescription:
      "Sourdough bread, accompanied by our aioli, grated Valencian tomato, and our sauce of the day.",
    price: "3.90",
    unit: false,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "ESTO SON BRAVAS!",
    englishTitle: "THESE ARE BRAVAS!",
    description: "Con salsa secreta y allioli tradicional.",
    englishDescription: "With secret sauce and traditional aioli.",
    price: false,
    unit: false,
    garnish: "6.90",
    halfGarnish: "4.50",
  },
  {
    title: "CALAMAR CRUJIENTE",
    englishTitle: "CRISPY SQUID",
    description: "Calamares fritos con salsa kimchi y cilantro.",
    englishDescription: "Fried calamari with kimchi sauce and cilantro.",
    price: "10.50",
    unit: false,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "CROQUETA DE JAMÓN",
    englishTitle: "HAM CROQUETTE",
    description: "",
    englishDescription: "",
    price: "2.90",
    unit: true,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "CROQUETA DE TERNERA ESTOFADA Y TARTUFO",
    englishTitle: "STEWED BEEF CROQUETTE AND TARTUF",
    description: "",
    englishDescription: "",
    price: "3.50",
    unit: true,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "CHICHARRÓN",
    englishTitle: "CHICHARRÓN",
    description: "De cerdo crujiente con pico de gallo y lima",
    englishDescription: "Crispy pork with pico de gallo and lime.",
    price: "6.90",
    unit: false,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "GUACAMOLE",
    englishTitle: "GUACAMOLE",
    description: "Con chips de yuca y tostones de plátano verde",
    englishDescription: "With yuca chips and green plantain tostones.",
    price: "8",
    unit: false,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "CRISPY CHICKEN",
    englishTitle: "CRISPY CHICKEN",
    description: "Contramuslo de pollo crujiente con mayo kimchi",
    englishDescription: "Crispy chicken thigh with kimchi mayo.",
    price: "8.75",
    unit: false,
    garnish: false,
    halfGarnish: false,
  },
  {
    title: "ESPÁRRAGOS CRUJIENTES",
    englishTitle: "CRISPY ASPARAGUS",
    description: "Con sweet chilli, mayonesa de aguacate y cilantro",
    englishDescription: "With sweet chili, avocado mayonnaise, and cilantro.",
    price: "8.50",
    unit: false,
    garnish: false,
    halfGarnish: false,
  },
];
